# Generated by Django 5.2.6 on 2025-09-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Ads.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('abadan', 'آبادان'), ('abadeh', 'آباده'), ('abyek', 'آبیک'), ('ahvaz', 'اهواز'), ('ajabshir', 'عجب\u200cشیر'), ('arak', 'اراک'), ('ardabil', 'اردبیل'), ('arsanjan', 'ارسنجان'), ('asaluyeh', 'عسلویه'), ('azarshahr', 'آذرشهر'), ('babolsar', 'بابلسر'), ('bandarabbas', 'بندرعباس'), ('bandarlengeh', 'بندرلنگه'), ('bojnurd', 'بجنورد'), ('borujerd', 'بروجرد'), ('bushehr', 'بوشهر'), ('birjand', 'بیرجند'), ('bukan', 'بوکان'), ('chabahar', 'چابهار'), ('damghan', 'دامغان'), ('dezful', 'دزفول'), ('divandarreh', 'دیواندره'), ('esfarayen', 'اسفراین'), ('fasa', 'فسا'), ('gorgan', 'گرگان'), ('hamadan', 'همدان'), ('ilam', 'ایلام'), ('iranshahr', 'ایرانشهر'), ('isfahan', 'اصفهان'), ('jahrom', 'جهرم'), ('jiroft', 'جیرفت'), ('karaj', 'کرج'), ('kashan', 'کاشان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('khorramabad', 'خرم\u200cآباد'), ('khoy', 'خوی'), ('lahijan', 'لاهیجان'), ('maragheh', 'مراغه'), ('marvdasht', 'مرودشت'), ('mashhad', 'مشهد'), ('miandoab', 'میاندوآب'), ('minab', 'میناب'), ('najafabad', 'نجف\u200cآباد'), ('nishapur', 'نیشابور'), ('orumiyeh', 'ارومیه'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('rasht', 'رشت'), ('sabzevar', 'سبزوار'), ('sanandaj', 'سنندج'), ('sari', 'ساری'), ('semnan', 'سمنان'), ('shahrekord', 'شهرکرد'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('tehran', 'تهران'), ('yazd', 'یزد'), ('zanjan', 'زنجان')], max_length=15)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads.category')),
            ],
        ),
    ]
