# Generated by Django 5.2.6 on 2025-09-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('is_images_for_this_property', models.BooleanField(default=True, verbose_name='تصاویر مربوط به همین ملک است؟')),
                ('price_per_meter', models.IntegerField(blank=True, null=True, verbose_name='قیمت هر متر')),
                ('floor', models.IntegerField(blank=True, choices=[(0, 'همکف'), (-1, 'زیرزمین'), (1, 'طبقه 1'), (2, 'طبقه 2'), (3, 'طبقه 3'), (4, 'طبقه 4'), (5, 'طبقه 5 و بالاتر')], null=True, verbose_name='طبقه')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('has_parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('has_storage', models.BooleanField(default=False, verbose_name='انباری')),
            ],
            options={
                'verbose_name': 'آگهی املاک',
                'verbose_name_plural': 'آگهی\u200cهای املاک',
            },
            bases=('Ads.ads',),
        ),
    ]
