# Generated by Django 5.2.6 on 2025-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_realestatead'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatead',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)'),
        ),
    ]
