# Generated by Django 5.2.6 on 2025-09-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_realestatead_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='میزان کارکرد خودرو به کیلومتر', null=True, verbose_name='کارکرد (کیلومتر)')),
                ('production_year', models.PositiveSmallIntegerField(verbose_name='سال تولید')),
                ('color', models.CharField(max_length=30, verbose_name='رنگ')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('model', models.CharField(max_length=50, verbose_name='مدل')),
                ('trim', models.CharField(max_length=50, verbose_name='تیپ')),
                ('insurance_expiry', models.DateField(verbose_name='مهلت بیمه شخص ثالث')),
                ('gearbox', models.CharField(choices=[('manual', 'دنده\u200cای'), ('automatic', 'اتوماتیک')], max_length=10, verbose_name='گیربکس')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزین'), ('diesel', 'دیزل'), ('cng', 'گاز CNG'), ('hybrid', 'هیبرید'), ('electric', 'برقی')], max_length=10, verbose_name='نوع سوخت')),
                ('base_price', models.PositiveIntegerField(verbose_name='قیمت پایه (تومان)')),
            ],
            options={
                'verbose_name': 'آگهی خودرو',
                'verbose_name_plural': 'آگهی\u200cهای خودرو',
            },
            bases=('Ads.ads',),
        ),
    ]
