# Generated by Django 5.2.6 on 2025-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_carad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='carad',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت بیمه شخص ثالث'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='production_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تولید'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='trim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تیپ'),
        ),
    ]
