# Generated by Django 5.2.6 on 2025-09-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_remove_carad_base_price_alter_carad_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('model_name', models.CharField(max_length=100, verbose_name='مدل دستگاه')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'کارکرده'), ('refurbished', 'بازسازی\u200cشده')], max_length=20, verbose_name='وضعیت کالا')),
                ('storage_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='حافظه داخلی (GB)')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='سیستم\u200cعامل')),
                ('warranty', models.BooleanField(default=False, verbose_name='دارای گارانتی')),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت گارانتی (ماه)')),
            ],
            options={
                'verbose_name': 'آگهی کالای دیجیتال',
                'verbose_name_plural': 'آگهی\u200cهای کالای دیجیتال',
            },
            bases=('Ads.ads',),
        ),
    ]
