# Generated by Django 5.2.6 on 2025-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_digitalproductad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('entertainment_type', models.CharField(choices=[('event', 'رویداد'), ('instrument', 'ساز موسیقی'), ('sport', 'لوازم ورزشی'), ('game', 'بازی'), ('other', 'سایر')], max_length=20, verbose_name='نوع سرگرمی')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'کارکرده')], max_length=10, verbose_name='وضعیت')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='برند')),
                ('genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='ژانر / دسته\u200cبندی')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگزاری')),
            ],
            options={
                'verbose_name': 'آگهی سرگرمی و فراغت',
                'verbose_name_plural': 'آگهی\u200cهای سرگرمی و فراغت',
            },
            bases=('Ads.ads',),
        ),
        migrations.CreateModel(
            name='HomeKitchenAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('material', models.CharField(max_length=50, verbose_name='جنس')),
                ('product_type', models.CharField(max_length=100, verbose_name='نوع محصول')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'کارکرده')], max_length=10, verbose_name='وضعیت کالا')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد / وزن')),
            ],
            options={
                'verbose_name': 'آگهی خانه و آشپزخانه',
                'verbose_name_plural': 'آگهی\u200cهای خانه و آشپزخانه',
            },
            bases=('Ads.ads',),
        ),
        migrations.CreateModel(
            name='IndustrialEquipmentAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='نوع تجهیزات')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='توان / قدرت')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='برند')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'کارکرده')], max_length=20, verbose_name='وضعیت')),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
            ],
            options={
                'verbose_name': 'آگهی تجهیزات و صنعتی',
                'verbose_name_plural': 'آگهی\u200cهای تجهیزات و صنعتی',
            },
            bases=('Ads.ads',),
        ),
        migrations.CreateModel(
            name='JobListingAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('position', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('location', models.CharField(max_length=100, verbose_name='محل کار')),
                ('employment_type', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('remote', 'دورکاری'), ('contract', 'قراردادی')], max_length=20, verbose_name='نوع همکاری')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='حقوق')),
                ('experience_required', models.PositiveIntegerField(blank=True, null=True, verbose_name='سابقه کار مورد نیاز (سال)')),
                ('education', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک تحصیلی')),
            ],
            options={
                'verbose_name': 'آگهی استخدام',
                'verbose_name_plural': 'آگهی\u200cهای استخدام',
            },
            bases=('Ads.ads',),
        ),
        migrations.CreateModel(
            name='PersonalItemAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'کارکرده')], max_length=10, verbose_name='وضعیت کالا')),
                ('item_type', models.CharField(max_length=50, verbose_name='نوع کالا')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='برند')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'آگهی وسایل شخصی',
                'verbose_name_plural': 'آگهی\u200cهای وسایل شخصی',
            },
            bases=('Ads.ads',),
        ),
        migrations.CreateModel(
            name='ServiceAd',
            fields=[
                ('ads_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ads.ads')),
                ('service_type', models.CharField(max_length=100, verbose_name='نوع خدمت')),
                ('experience_years', models.PositiveIntegerField(verbose_name='سابقه کار (سال)')),
                ('service_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل ارائه خدمت')),
                ('is_remote', models.BooleanField(default=False, verbose_name='امکان ارائه غیرحضوری')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'آگهی خدمات',
                'verbose_name_plural': 'آگهی\u200cهای خدمات',
            },
            bases=('Ads.ads',),
        ),
    ]
