# Generated by Django 5.2.6 on 2025-09-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0007_entertainmentad_homekitchenad_industrialequipmentad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': ' آگهی', 'verbose_name_plural': 'همه آگهی \u200cها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads_images/')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیح تصویر')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ads.ads')),
            ],
            options={
                'verbose_name': 'تصویر آگهی',
                'verbose_name_plural': 'تصاویر آگهی\u200cها',
            },
        ),
    ]
